INSERT overwrite TABLE la_shipment_fact
SELECT shipment_id ,
       vendor_tracking_id ,
       shipment_current_status ,
       shipment_current_status_date_key ,
       shipment_current_status_time_key ,
       payment_type ,
       destination_geo_id_key ,
       ekl_shipment_type ,
       customer_promise_date_key ,
       customer_promise_time_key ,
       logistics_promise_date_key ,
       logistics_promise_time_key ,
       shipment_created_at_date_key ,
       shipment_created_at_time_key ,
       vendor_id_key ,
       shipment_carrier ,
       fsd_assigned_hub_id_key ,
       fsd_last_current_hub_id_key ,
       fsd_last_current_hub_type ,
       shipment_inscan_time ,
       shipment_rto_create_time ,
       fsd_last_received_time ,
       fsd_number_of_ofd_attempts ,
       fsd_assignedhub_expected_time ,
       fsd_assignedhub_received_time ,
       fsd_returnedtoekl_time ,
       fsd_receivedbyekl_time ,
       merchant_reference_id ,
       ekl_delivery_datetime ,
       ekl_delivery_date_key ,
       ekl_delivery_time_key ,
       shipment_first_ofd_datetime ,
       shipment_last_ofd_datetime ,
       vendor_dispatch_datetime ,
       ekl_billable_weight ,
       tpl_first_ofd_time ,
       tpl_last_ofd_time ,
       fsd_assigned_hub_sent_datetime ,
       shipment_first_consignment_id ,
       shipment_last_consignment_id ,
       openbox_reject_datetime ,
       merchant_id ,
       fsd_first_dh_received_datetime ,
       shipment_first_consignment_create_date_key ,
       shipment_first_consignment_create_time_key ,
       shipment_origin_facility_id_key ,
       fsd_firstundeliverystatus ,
       rvp_pickup_complete_datetime ,
       shipment_rvp_pk_number_of_attempts ,
       end_state_datetime ,
       fsd_last_dhhub_sent_datetime ,
       rvp_hub_id ,
       rvp_hub_id_key ,
       rvp_origin_geo_id_key ,
       rvp_destination_facility_key ,
       shipment_value ,
       cod_amount_to_collect ,
       runsheet_close_datetime ,
       runsheet_close_date_key ,
       shipment_created_at_datetime ,
       shipment_last_consignment_create_datetime ,
       shipment_last_consignment_eta_in_sec ,
	   shipment_last_consignment_eta_datetime ,
       shipment_last_consignment_conn_id ,
       shipment_first_consignment_create_datetime ,
       tasklist_tracking_id ,
       ekl_facility_id ,
       last_tasklist_agent_id ,
       last_tasklist_updated_at ,
       tasklist_type ,
       last_tasklist_id ,
       tasklist_status ,
       runsheet_id ,
       last_tasklist_agent_id_key ,
       ekl_facility_id_key ,
       seller_id ,
       payment_mode ,
       pos_id ,
       transaction_id ,
       agent_id ,
       amount_collected ,
       seller_type ,
       shipment_dg_flag ,
       shipment_fragile_flag ,
       seller_id_key ,
       pos_id_key ,
       shipment_agent_id_key ,
       dummy1 ,
       dummy2 ,
       lzn_classification ,
       vendor_name
FROM
  (SELECT DISTINCT shipment_id ,
                   vendor_tracking_id ,
                   shipment_current_status ,
                   shipment_current_status_date_key ,
                   shipment_current_status_time_key ,
                   payment_type ,
                   destination_geo_id_key ,
                   ekl_shipment_type ,
                   customer_promise_date_key ,
                   customer_promise_time_key ,
                   logistics_promise_date_key ,
                   logistics_promise_time_key ,
                   shipment_created_at_date_key ,
                   shipment_created_at_time_key ,
                   vendor_id_key ,
                   shipment_carrier ,
                   fsd_assigned_hub_id_key ,
                   fsd_last_current_hub_id_key ,
                   fsd_last_current_hub_type ,
                   shipment_inscan_time ,
                   shipment_rto_create_time ,
                   fsd_last_received_time ,
                   fsd_number_of_ofd_attempts ,
                   fsd_assignedhub_expected_time ,
                   fsd_assignedhub_received_time ,
                   fsd_returnedtoekl_time ,
                   fsd_receivedbyekl_time ,
                   merchant_reference_id ,
                   ekl_delivery_datetime ,
                   ekl_delivery_date_key ,
                   ekl_delivery_time_key ,
                   shipment_first_ofd_datetime ,
                   shipment_last_ofd_datetime ,
                   vendor_dispatch_datetime ,
                   ekl_billable_weight ,
                   tpl_first_ofd_time ,
                   tpl_last_ofd_time ,
                   fsd_assigned_hub_sent_datetime ,
                   shipment_first_consignment_id ,
                   shipment_last_consignment_id ,
                   openbox_reject_datetime ,
                   merchant_id ,
                   fsd_first_dh_received_datetime ,
                   shipment_first_consignment_create_date_key ,
                   shipment_first_consignment_create_time_key ,
                   shipment_origin_facility_id_key ,
                   fsd_firstundeliverystatus ,
                   rvp_pickup_complete_datetime ,
                   shipment_rvp_pk_number_of_attempts ,
                   end_state_datetime ,
                   fsd_last_dhhub_sent_datetime ,
                   rvp_hub_id ,
                   lookupkey('facility_id', rvp_hub_id) AS rvp_hub_id_key ,
                   rvp_origin_geo_id_key ,
                   rvp_destination_facility_key ,
                   shipment_value ,
                   COD_amount_to_collect AS cod_amount_to_collect ,
                   runsheet_close_datetime ,
                   lookup_date(runsheet_close_datetime) AS runsheet_close_date_key ,
                   shipment_created_at_datetime ,
                   shipment_last_consignment_create_datetime ,
                   shipment_last_consignment_eta_in_sec ,
				   shipment_last_consignment_eta_datetime ,
                   shipment_last_consignment_conn_id ,
                   shipment_first_consignment_create_datetime ,
                   tasklist_tracking_id ,
                   ekl_facility_id ,
                   last_tasklist_agent_id ,
                   last_tasklist_updated_at ,
                   tasklist_type ,
                   last_tasklist_id ,
                   tasklist_status ,
                   runsheet_id ,
                   last_tasklist_agent_id_key ,
                   ekl_facility_id_key ,
                   seller_id ,
                   payment_mode ,
                   pos_id ,
                   transaction_id ,
                   agent_id ,
                   amount_collected ,
                   seller_type ,
                   shipment_dg_flag ,
                   shipment_fragile_flag ,
                   lookupkey('seller_id', seller_id) AS seller_id_key ,
                   lookupkey('device_id', CAST(SPLIT(pos_id, "-") [1] AS INT)) AS pos_id_key ,
  					lookupkey('agent_id', agent_id) AS shipment_agent_id_key ,
					pincode_location_type AS dummy1 ,
					is_cpu_vendor AS dummy2 ,
					lzn_classification ,
					vendor_name
			    	FROM
			    	  ( SELECT sv.entityid AS shipment_id ,
           sv.sv_vendor_tracking_id AS vendor_tracking_id ,
           sv.shipment_current_status AS shipment_current_status ,
           lookup_date(cast(sv.updatedat / 1000 AS TIMESTAMP)) AS shipment_current_status_date_key ,
           lookup_time(cast(sv.updatedat / 1000 AS TIMESTAMP)) AS shipment_current_status_time_key ,
           sv.payment_type AS payment_type ,
           lookupkey('pincode', sv.dest_address_pincode) AS destination_geo_id_key ,
           sv.shipment_type AS ekl_shipment_type ,
           lookup_date(sv.customer_sla) AS customer_promise_date_key ,
           lookup_time(sv.customer_sla) AS customer_promise_time_key ,
           lookup_date(sv.design_sla) AS logistics_promise_date_key ,
           lookup_time(sv.design_sla) AS logistics_promise_time_key ,
           lookup_date(sv.created_at) AS shipment_created_at_date_key ,
           lookup_time(sv.created_at) AS shipment_created_at_time_key ,
           sv.created_at AS shipment_created_at_datetime ,
           lookupkey('vendor_id', sv.vendor_id) AS vendor_id_key ,
           ( CASE WHEN sv.vendor_id = 200 THEN 'flipkartlogistics' WHEN sv.vendor_id = 207 THEN 'flipkartlogistics-cod' WHEN sv.vendor_id = 242 THEN 'flipkartreverse'  ELSE NULL END ) AS vendor_name ,
           IF ( sv.vendor_id = '' ,
                               'VNF' ,
                               'FSD' ) AS shipment_carrier ,
              lookupkey('facility_id', IF ( NOT isnull(sv.fsd_assigned_hub_id) ,sv.fsd_assigned_hub_id ,sreh.fsd_assigned_hub_id )) AS fsd_assigned_hub_id_key ,
              lookupkey('facility_id', sv.fsd_last_current_hub_id) AS fsd_last_current_hub_id_key ,
              sv.fsd_last_current_hub_type AS fsd_last_current_hub_type ,
              sv.ekl_billable_weight AS ekl_billable_weight ,
              slog.merchant_reference_id ,
              sc.shipment_first_consignment_id ,
              sc.shipment_last_consignment_id ,
              sc.shipment_last_consignment_create_datetime ,
              sc.shipment_last_consignment_eta_in_sec ,
			  sc.shipment_last_consignment_eta_datetime ,
              sc.shipment_last_consignment_conn_id ,
              sreh.shipment_inscan_time ,
              sreh.shipment_rto_create_time ,
              sreh.fsd_last_received_time ,
              sreh.fsd_number_of_ofd_attempts ,
              sreh.tpl_number_of_attempts ,
              sreh.fsd_assignedhub_expected_time ,
              sreh.fsd_assignedhub_received_time ,
              sreh.fsd_returnedtoekl_time ,
              sreh.fsd_receivedbyekl_time ,
              sreh.ekl_delivery_datetime ,
              lookup_date(sreh.ekl_delivery_datetime) AS ekl_delivery_date_key ,
              lookup_time(sreh.ekl_delivery_datetime) AS ekl_delivery_time_key ,
              sreh.shipment_first_ofd_datetime ,
              sreh.shipment_last_ofd_datetime ,
              sreh.vendor_dispatch_datetime ,
              sreh.tpl_first_ofd_time ,
              sreh.tpl_last_ofd_time ,
              sreh.fsd_assigned_hub_sent_datetime ,
              sreh.openbox_reject_datetime ,
              slog.merchant_id ,
              sreh.fsd_first_DH_received_datetime ,
              sreh.shipment_value ,
              sreh.runsheet_close_datetime ,
              sreh.COD_amount_to_collect ,
              sreh.payment_mode ,
              sc.shipment_first_consignment_create_datetime ,
              sc.shipment_first_consignment_create_date_key ,
              sc.shipment_first_consignment_create_time_key ,
              lookupkey('facility_id', IF ( sv.source_address_id IS NOT NULL
                                           AND sv.source_address_id <> 0 ,sv.source_address_id ,sourceFacility.source_facility_id )) AS shipment_origin_facility_id_key ,
              sreh_undel.fsd_firstUndeliveryStatus ,
              sreh.rvp_pickup_complete_datetime ,
              sreh.shipment_rvp_pk_number_of_attempts ,
              sreh.end_state_datetime ,
              sreh.fsd_last_dhhub_sent_datetime ,
              sreh_temp_02.rvp_hub_id AS rvp_hub_id ,
              IF ( sv.shipment_type = 'rvp' ,
                                      lookupkey('pincode', sv.rvp_origin_geo_id) ,
                                      NULL ) AS rvp_origin_geo_id_key ,
                 IF ( sv.shipment_type = 'rvp' ,
                                         lookupkey('facility_id', IF ( sv.destination_address_id IS NOT NULL
                                                                      AND sv.destination_address_id <> 0 ,sv.destination_address_id ,sourceFacility.source_facility_id )) ,
                                         NULL) AS rvp_destination_facility_key ,
                    runsheet_details.tasklist_tracking_id AS tasklist_tracking_id ,
                    runsheet_details.ekl_facility_id AS ekl_facility_id ,
                    runsheet_details.last_tasklist_agent_id AS last_tasklist_agent_id ,
                    runsheet_details.last_tasklist_updated_at AS last_tasklist_updated_at ,
                    runsheet_details.tasklist_type AS tasklist_type ,
                    runsheet_details.last_tasklist_id AS last_tasklist_id ,
                    runsheet_details.tasklist_status AS tasklist_status ,
                    runsheet_details.runsheet_id AS runsheet_id ,
                    runsheet_details.last_tasklist_agent_id_key AS last_tasklist_agent_id_key ,
                    runsheet_details.ekl_facility_id_key AS ekl_facility_id_key ,
                    sv.seller_id AS seller_id ,
                    sv.pos_id AS pos_id ,
                    sv.transaction_id AS transaction_id ,
                    sv.agent_id AS agent_id ,
                    sv.amount_collected AS amount_collected ,
                    IF ( lower(sv.source_address_type) = 'warehouse' ,
                                                         IF ( lower(sv.seller_id) = 'wsr' ,
                                                                                    'WSR' ,
                                                                                    IF ( lower(sv.seller_id) = 'myn' ,
                                                                                                               'MYN' ,
                                                                                                               'FA' )) , IF ( lower(sv.source_address_type) = 'mp_non_fbf_seller' ,
                                                                                                                                                              'Non-FA' ,
                                                                                                                                                              IF ( lower(sv.source_address_type) = 'customer' ,
                                                                                                                                                                                                   IF ( lower(sv.seller_id) = 'myn' ,
'MYN' ,
IF ( lower(sv.seller_id) = 'wsr' ,
                           'WSR' ,
                           IF ( lower(sv.seller_type) = 'warehouse' ,
                                                        'FA' ,
                                                        'Non-FA' ))) ,NULL))) AS seller_type ,
                       IF ( concat_ws("-", sv.sv_attribute) LIKE '%dangerous%' ,
                                                                 1 ,
                                                                 0 ) AS shipment_dg_flag ,
                          IF ( concat_ws("-", sv.sv_attribute) LIKE '%ragile%' ,
                                                                    1 ,
                                                                    0 ) AS shipment_fragile_flag ,
                             lt.location_type AS pincode_location_type ,
                             runsheet_details.is_cpu_vendor ,
                             lzn.lzn_classification AS lzn_classification
   FROM
( SELECT entityid AS entityid ,
         `data`.vendor_tracking_id AS sv_vendor_tracking_id ,
         `data`.STATUS AS shipment_current_status ,
         updatedat AS updatedat ,
         `data`.payment_type AS payment_type ,
         `data`.destination_address.pincode AS dest_address_pincode ,
         `data`.shipment_type AS shipment_type ,
         `data`.customer_sla AS customer_sla ,
         `data`.design_sla AS design_sla ,
         `data`.created_at AS created_at ,
         `data`.vendor_id AS vendor_id ,
         `data`.assigned_address.id AS fsd_assigned_hub_id ,
         `data`.current_address.id AS fsd_last_current_hub_id ,
         `data`.current_address.type AS fsd_last_current_hub_type ,
         `data`.billable_weight AS ekl_billable_weight ,
         `data`.source_address.id AS source_address_id ,
         `data`.source_address.pincode AS rvp_origin_geo_id ,
         `data`.destination_address.id AS destination_address_id ,
         `data`.shipment_items [0].seller_id AS seller_id ,
         `data`.payment.payment_details [0].device_id AS pos_id ,
         `data`.payment.payment_details [0].transaction_id AS transaction_id ,
         `data`.payment.payment_details [0].agent_id AS agent_id ,
         `data`.payment.amount_collected.value AS amount_collected ,
         `data`.source_address.type AS source_address_type ,
         `data`.destination_address.type AS seller_type ,
         `data`.attributes AS sv_attribute ,
         IF ( `data`.shipment_type = 'rvp' ,
                                     `data`.source_address.pincode ,
                                     `data`.destination_address.pincode ) AS location_pincode ,
            IF ( `data`.shipment_type = 'rvp' ,
                                        `data`.destination_address.pincode ,
                                        `data`.source_address.pincode ) AS source_address_pincode,
            IF ( `data`.shipment_type = 'rvp' ,
                                        `data`.source_address.pincode ,
                                        `data`.destination_address.pincode ) AS destination_address_pincode
 FROM bigfoot_snapshot.dart_wsr_scp_ekl_shipment_4_view_total
 WHERE ( `data`.source_address.id IN ( 563 ,
                                       564 ,
                                       565 ,
                                       566 ,
                                       567 ,
                                       1280 ,
                                       1282 ,
                                       1288 ,
                                       1511 ,
                                       1757 ,
                                       1950 ,
                                       2043 ,
                                       3594 ,
                                       3612 ,
                                       3620 ,
                                       3621 ,
                                       3622 ,
                                       3623 )
        OR `data`.destination_address.id IN ( 563 ,
                                              564 ,
                                              565 ,
                                              566 ,
                                              567 ,
                                              1280 ,
                                              1282 ,
                                              1288 ,
                                              1511 ,
                                              1757 ,
                                              1950 ,
                                              2043 ,
                                              3594 ,
                                              3612 ,
                                              3620 ,
                                              3621 ,
                                              3622 ,
                                              3623 ) )
   AND ( `data`.vendor_id IN ( 200 ,
                               207 ,
                               242 )
        OR `data`.vendor_id = '' )) sv
   LEFT OUTER JOIN bigfoot_common.la_lzn_classification lzn ON ( sv.destination_address_pincode = lzn.destination_pincode
                                                                AND sv.source_address_pincode = lzn.source_pincode )
   LEFT OUTER JOIN
( SELECT DISTINCT refid AS shipment_id ,
                  `data`.merchant_id AS merchant_id ,
                  `data`.merchant_reference_id AS merchant_reference_id
 FROM bigfoot_snapshot.dart_wsr_scp_ekl_b2clogisticsrequest_1_view_total LATERAL VIEW explode(`data`.ekl_reference_ids) reference_id AS refid ) slog ON sv.entityid = slog.shipment_id
   LEFT OUTER JOIN
( SELECT C.shipment_first_consignment_id AS shipment_first_consignment_id ,
         C.shipment_last_consignment_id AS shipment_last_consignment_id ,
         lookup_date(to_date(from_unixtime(shipment_first_consignment_create_datetime))) AS shipment_first_consignment_create_date_key ,
         lookup_time(from_unixtime(shipment_first_consignment_create_datetime)) AS shipment_first_consignment_create_time_key ,
         lookup_date(to_date(from_unixtime(shipment_last_consignment_create_datetime))) AS shipment_last_consignment_create_date_key ,
         C.tracking_id AS vendor_tracking_id ,
         from_unixtime(shipment_last_consignment_create_datetime) AS shipment_last_consignment_create_datetime ,
         shipment_last_consignment_eta_in_sec ,
		 shipment_last_consignment_eta_datetime ,
         shipment_last_consignment_conn_id ,
         from_unixtime(shipment_first_consignment_create_datetime) AS shipment_first_consignment_create_datetime
 FROM
   ( SELECT B.shipment_first_consignment_id ,
            B.shipment_first_consignment_create_datetime ,
            B.row_n ,
            B.shipment_last_consignment_id ,
            B.shipment_last_consignment_create_datetime ,
            B.shipment_last_consignment_eta_in_sec ,
			B.shipment_last_consignment_eta_datetime ,
            B.shipment_last_consignment_conn_id ,
            B.l_row_n ,
            B.tracking_id
    FROM
      ( SELECT first_value(A.consignment_id) OVER ( PARTITION BY A.tracking_id
                                                   ORDER BY A.first_time ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS shipment_first_consignment_id ,
               first_value(A.first_time) OVER ( PARTITION BY A.tracking_id
                                               ORDER BY A.first_time ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS shipment_first_consignment_create_datetime ,
               row_number() OVER ( PARTITION BY A.tracking_id
                                  ORDER BY A.first_time ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS row_n ,
               first_value(A.consignment_id) OVER ( PARTITION BY A.tracking_id
                                                   ORDER BY A.first_time DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS shipment_last_consignment_id ,
               first_value(A.conn_id) OVER ( PARTITION BY A.tracking_id
                                            ORDER BY A.first_time DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS shipment_last_consignment_conn_id ,
               first_value(A.first_time) OVER ( PARTITION BY A.tracking_id
                                               ORDER BY A.first_time DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS shipment_last_consignment_create_datetime ,
               first_value(A.eta_in_sec) OVER ( PARTITION BY A.tracking_id
                                               ORDER BY A.first_time DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS shipment_last_consignment_eta_in_sec ,
			   first_value(A.eta_datatime) OVER ( PARTITION BY A.tracking_id
											ORDER BY A.first_time DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS shipment_last_consignment_eta_datetime ,
               row_number() OVER ( PARTITION BY A.tracking_id
                                  ORDER BY A.first_time DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS l_row_n ,
               tracking_id
       FROM
         ( SELECT entityid ,
cast(split(entityid, "-") [1] AS INT) AS consignment_id ,
TRID AS tracking_id ,
`data`.connection_id AS Conn_id ,
min(`data`.connection_estimated_tat) AS eta_in_sec ,
min(`data`.eta) as eta_datatime ,
min(unix_timestamp(`data`.created_at)) AS first_time
FROM bigfoot_journal.dart_wsr_scp_ekl_shipmentgroup_3 LATERAL VIEW explode(`data`.shipments) exploded_table AS TRID
WHERE `data`.type = 'consignment'
AND `data`.source_location.id IN ( 599 ,
600 ,
601 ,
602 ,
603 ,
1281 ,
1289 ,
1517 ,
1758 ,
1954 ,
2017 ,
3598 ,
4066 ,
4065 ,
4064 ,
4061 ,
4060 ,
465 )
GROUP BY entityid ,
TRID ,
`data`.connection_id
				   ) A ) B
    WHERE B.row_n = 1 ) C ) sc ON sv.sv_vendor_tracking_id = sc.vendor_tracking_id
   LEFT OUTER JOIN
( SELECT entityid ,
         min(IF ( `data`.STATUS = 'received'
                 AND upper(`data`.current_address.type) IN ( 'FKL_FACILITY' ,'MOTHER_HUB' ) ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS shipment_inscan_time ,
         min(IF ( `data`.shipment_type LIKE '%rto%' ,from_utc_timestamp(updatedat, 'GMT') ,NULL )) AS shipment_rto_create_time ,
         max(IF ( `data`.STATUS = 'Received' ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS fsd_last_received_time ,
         count(DISTINCT IF ( `data`.STATUS IN ('Out_For_Delivery') ,CONCAT ( `data`.STATUS ,to_date(from_unixtime(unix_timestamp(`data`.updated_at))) ) ,NULL )) AS fsd_number_of_ofd_attempts ,
         count(DISTINCT IF ( lower(`data`.STATUS) IN ( 'undelivered_attempted' ,'delivered' ) ,CONCAT ( `data`.STATUS ,to_date(from_unixtime(unix_timestamp(`data`.updated_at))) ) ,NULL )) AS tpl_number_of_attempts ,
         min(IF ( `data`.current_address.id = `data`.assigned_address.id
                 AND `data`.STATUS = 'Expected' ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS fsd_assignedhub_expected_time ,
         min(IF ( `data`.current_address.id = `data`.assigned_address.id
                 AND `data`.STATUS = 'Received' ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS fsd_assignedhub_received_time ,
         min(IF ( `data`.STATUS = 'Returned_To_Ekl' ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS fsd_returnedtoekl_time ,
         min(IF ( `data`.STATUS = 'Received_By_Ekl' ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS fsd_receivedbyekl_time ,
         min(IF ( lower(`data`.STATUS) IN ( 'delivered' ,'delivery_update' ) ,from_utc_timestamp(updatedat, 'GMT') ,NULL )) AS runsheet_close_datetime ,
         min(IF ( lower(`data`.STATUS) IN ( 'delivered' ,'delivery_update' ) ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS ekl_delivery_datetime ,
         min(IF ( `data`.STATUS IN ('Out_For_Delivery') ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS shipment_first_ofd_datetime ,
         max(IF ( `data`.STATUS IN ('Out_For_Delivery') ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS shipment_last_ofd_datetime ,
         min(IF ( `data`.STATUS = 'dispatched_to_vendor' ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS vendor_dispatch_datetime ,
         min(IF ( lower(`data`.STATUS) IN ( 'undelivered_attempted' ,'delivered' )
                 AND `data`.vendor_id NOT IN ( 200 ,207 ) ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS tpl_first_ofd_time ,
         max(IF ( lower(`data`.STATUS) IN ( 'undelivered_attempted' ,'delivered' )
                 AND `data`.vendor_id NOT IN ( 200 ,207 ) ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS tpl_last_ofd_time ,
         min(IF ( `data`.current_address.id = `data`.assigned_address.id
                 AND `data`.STATUS = 'Sent' ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS fsd_assigned_hub_sent_datetime ,
         min(IF ( lower(`data`.STATUS) = 'undelivered_order_rejected_opendelivery' ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS openbox_reject_datetime ,
         min(IF ( `data`.STATUS = 'Expected' ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS received_at_source_facility ,
         min(IF ( `data`.STATUS IN ( 'Received' ,'Undelivered_Not_Attended' ,'Error' )
                 AND `data`.current_address.type IN ( 'DELIVERY_HUB' ,'BULK_HUB' ) ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS fsd_first_dh_received_datetime ,
         min(IF ( `data`.STATUS = 'PICKUP_Picked_Complete' ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS rvp_pickup_complete_datetime ,
         count(DISTINCT IF ( `data`.STATUS = 'PICKUP_Out_For_Pickup' ,CONCAT ( `data`.STATUS ,to_date(from_unixtime(unix_timestamp(`data`.updated_at))) ) ,NULL )) AS shipment_rvp_pk_number_of_attempts ,
         max(IF ( lower(`data`.STATUS) IN ( 'lost' ,'not_received' ,'reshipped' ,'received_by_merchant' ,'returned_to_seller' ,'delivered' ) ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL )) AS end_state_datetime ,
         max(IF ( `data`.STATUS = 'Sent'
                 AND `data`.current_address.type IN ( 'DELIVERY_HUB' ,'BULK_HUB' ) ,from_unixtime(unix_timestamp(`data`.updated_at)) ,IF ( `data`.STATUS = 'Expected'
                                                                                                                                          AND `data`.current_address.type IN ( 'FKL_FACILITY' ,'MOTHER_HUB' ) ,from_unixtime(unix_timestamp(`data`.updated_at)) ,NULL ))) AS fsd_last_dhhub_sent_datetime ,
         min(`data`.value.value) AS shipment_value ,
         min(`data`.amount_to_collect.value) AS COD_amount_to_collect ,
         max(`data`.payment.payment_details.mode [0]) AS payment_mode ,
         min(IF ( lower(`data`.STATUS) IN ('inscan_success') ,`data`.assigned_address.id ,NULL )) AS fsd_assigned_hub_id 
	FROM bigfoot_journal.dart_wsr_scp_ekl_shipment_4 
                             GROUP BY entityid) sreh ON (sreh.entityid = sv.entityid)
   LEFT OUTER JOIN
     (SELECT entityid ,
             `data`.updated_at AS updated_at ,
             `data`.current_address.id AS source_facility_id
      FROM bigfoot_journal.dart_wsr_scp_ekl_shipment_4
      WHERE `data`.STATUS = 'expected'
        AND `data`.current_address.type = 'FKL_FACILITY'
        ) sourceFacility ON (sourceFacility.updated_at = sreh.received_at_source_facility
                                                AND sourceFacility.entityid = sv.entityid)
   LEFT OUTER JOIN
     (SELECT entityId ,
             fsd_firstundeliverystatus
      FROM
        (SELECT entityId ,
                first_value(`data`.STATUS) OVER (PARTITION BY entityId
                                                 ORDER BY `data`.updated_at ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS fsd_firstundeliverystatus ,
                first_value(`data`.updated_at) OVER (PARTITION BY entityId
                                                     ORDER BY `data`.updated_at ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS fsd_firstUndeliveryStatus_updated_at ,
                row_number() OVER (PARTITION BY entityId
                                   ORDER BY `data`.updated_at ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS ROW_ASC
         FROM bigfoot_journal.dart_wsr_scp_ekl_shipment_4 sreh_temp_00
         WHERE lower(`data`.STATUS) LIKE '%undelivered%'
           AND lower(`data`.STATUS) NOT IN ('undelivered_not_attempted' ,
                                            'undelivered_not_attended')
           ) sreh_temp_01
      WHERE sreh_temp_01.ROW_ASC = 1) sreh_undel ON (sreh_undel.entityid = sv.entityid)
   LEFT OUTER JOIN
     (SELECT entityId ,
             `data`.current_address.id AS rvp_hub_id ,
             from_unixtime(unix_timestamp(`data`.updated_at)) AS updated_received
      FROM bigfoot_journal.dart_wsr_scp_ekl_shipment_4
      WHERE `data`.STATUS = 'Expected'
        ) sreh_temp_02 ON (sreh_temp_02.entityId = sreh.entityId
                                              AND sreh_temp_02.updated_received = sreh.received_at_source_facility)
   LEFT OUTER JOIN
     (SELECT DISTINCT `data`.group_id AS last_group_id ,
                      `data`.cutoff AS last_conn_cutoff_in_sec
      FROM bigfoot_snapshot.dart_wsr_scp_ekl_connection_1_11_view_total) last_conn ON last_conn.last_group_id = sc.shipment_last_consignment_conn_id
   LEFT OUTER JOIN
     (SELECT tasklist_tracking_id ,
             ekl_facility_id ,
             last_tasklist_agent_id ,
             last_tasklist_updated_at ,
             tasklist_type ,
             last_tasklist_id ,
             tasklist_status ,
             runsheet_id ,
             last_tasklist_agent_id_key ,
             ekl_facility_id_key ,
             IF (last_tasklist_agent_id IN ('85070' ,
                                            '85071' ,
                                            '85073' ,
                                            '85068' ,
                                            '85072' ,
                                            '85069' ,
                                            '83267' ,
                                            '85443' ,
                                            '83268' ,
                                            '83271' ,
                                            '85442' ,
                                            '83270' ,
                                            '85444' ,
                                            '85650' ,
                                            '85441' ,
                                            '85446' ,
                                            '85651' ,
                                            '85653' ,
                                            '85652' ,
                                            '83269' ,
                                            '74352' ,
                                            '74353' ,
                                            '73788' ,
                                            '73793' ,
                                            '73798' ,
                                            '85405' ,
                                            '73766' ,
                                            '85402' ,
                                            '73794' ,
                                            '73790' ,
                                            '73797' ,
                                            '85406' ,
                                            '73791' ,
                                            '73787' ,
                                            '73789' ,
                                            '85403' ,
                                            '73786' ,
                                            '73796' ,
                                            '73792' ,
                                            '73768' ,
                                            '73795' ,
                                            '85404' ,
                                            '73779' ,
                                            '77288' ,
                                            '73767' ,
                                            '73780' ,
                                            '73773' ,
                                            '73777' ,
                                            '85973' ,
                                            '73774' ,
                                            '73775' ,
                                            '77290' ,
                                            '73776' ,
                                            '77289' ,
                                            '73778' ,
                                            '74496' ,
                                            '74499' ,
                                            '74354' ,
                                            '79298' ,
                                            '79299' ,
                                            '82779') ,1 ,
                                                      0) AS is_cpu_vendor
      FROM bigfoot_external_neo.scp_ekl__la_shipment_runsheet_fact) runsheet_details ON sv.sv_vendor_tracking_id = runsheet_details.last_tasklist_id
   LEFT OUTER JOIN
     (SELECT DISTINCT pincode ,
                      location_type
      FROM bigfoot_common.large_pincode_location_type) lt ON lt.pincode = sv.location_pincode) FINAL
UNION
SELECT DISTINCT l1_fact.shipment_reference_ids AS shipment_id ,
        l1_fact.vendor_tracking_id ,
        l1_fact.shipment_current_status ,
        l1_fact.shipment_current_status_date_key ,
        l1_fact.shipment_current_status_time_key ,
        l1_fact.payment_type ,
        l1_fact.destination_pincode_key AS destination_geo_id_key ,
        (CASE
             WHEN l1_fact.rto_flag = 1
                  AND l1_fact.shipment_movement_type = 'Outgoing' THEN 'approved_rto'
             WHEN l1_fact.rto_flag = 0
                  AND l1_fact.shipment_movement_type = 'Outgoing' THEN 'forward'
             WHEN l1_fact.shipment_movement_type = 'Incoming' THEN 'rvp'
             ELSE NULL
         END) AS ekl_shipment_type ,
        l1_fact.customer_sla_date_key AS customer_promise_date_key ,
        l1_fact.customer_sla_time_key AS customer_promise_time_key ,
        l1_fact.design_sla_date_key AS logistics_promise_date_key ,
        l1_fact.design_sla_time_key AS logistics_promise_time_key ,
        lookup_date(created_at) AS shipment_created_at_date_key ,
        lookup_time(created_at) AS shipment_created_at_time_key ,
		NULL AS vendor_id_key ,
		'3PL' AS shipment_carrier ,
		NULL AS fsd_assigned_hub_id_key ,
		NULL AS fsd_last_current_hub_id_key ,
		NULL AS fsd_last_current_hub_type ,
		NULL AS shipment_inscan_time ,
		l1_fact.rto_request_first_datetime AS shipment_rto_create_time ,
		NULL AS fsd_last_received_time ,
		NULL AS fsd_number_of_ofd_attempts ,
		NULL AS fsd_assignedhub_expected_time ,
		NULL AS fsd_assignedhub_received_time ,
		NULL AS fsd_returnedtoekl_time ,
		NULL AS fsd_receivedbyekl_time ,
		l1_fact.shipment_reference_ids AS merchant_reference_id ,
		l1_fact.delivered_first_datetime AS ekl_delivery_datetime ,
		l1_fact.delivered_first_date_key AS ekl_delivery_date_key ,
		l1_fact.delivered_first_time_key AS ekl_delivery_time_key ,
		NULL AS shipment_first_ofd_datetime ,
		NULL AS shipment_last_ofd_datetime ,
		l1_fact.dispatched_to_facility_first_date_key AS vendor_dispatch_datetime ,
		l1_fact.volumetric_weight AS ekl_billable_weight ,
		l1_fact.out_for_delivery_first_datetime AS tpl_first_ofd_time ,
		l0_fact.out_for_delivery_last_datetime AS tpl_last_ofd_time ,
		NULL AS fsd_assigned_hub_sent_datetime ,
		NULL AS shipment_first_consignment_id ,
		NULL AS shipment_last_consignment_id ,
		NULL AS openbox_reject_datetime ,
		NULL AS merchant_id ,
		NULL AS fsd_first_dh_received_datetime ,
		NULL AS shipment_first_consignment_create_date_key ,
		NULL AS shipment_first_consignment_create_time_key ,
		dim.ekl_facility_hive_dim_key AS shipment_origin_facility_id_key ,
		l1_fact.undelivered_attempted_first_secondary_status AS fsd_firstundeliverystatus ,
		l1_fact.rvp_pickup_completed_first_datetime AS rvp_pickup_complete_datetime ,
		NULL AS shipment_rvp_pk_number_of_attempts ,
		NULL AS end_state_datetime ,
		NULL AS fsd_last_dhhub_sent_datetime ,
		NULL AS rvp_hub_id ,
		NULL AS rvp_hub_id_key ,
		NULL AS rvp_origin_geo_id_key ,
		NULL AS rvp_destination_facility_key ,
		l1_fact.shipment_value ,
		l1_fact.amount_to_collect_value AS COD_amount_to_collect ,
		NULL AS runsheet_close_datetime ,
		NULL AS runsheet_close_date_key ,
		l1_fact.created_at AS shipment_created_at_datetime ,
		NULL AS shipment_last_consignment_create_datetime ,
		NULL AS shipment_last_consignment_eta_in_sec ,
		NULL AS shipment_last_consignment_eta_datetime ,
		NULL AS shipment_last_consignment_conn_id ,
		NULL AS shipment_first_consignment_create_datetime ,
		NULL AS tasklist_tracking_id ,
		NULL AS ekl_facility_id ,
		NULL AS last_tasklist_agent_id ,
		NULL AS last_tasklist_updated_at ,
		NULL AS tasklist_type ,
		NULL AS last_tasklist_id ,
		NULL AS tasklist_status ,
		NULL AS runsheet_id ,
		NULL AS last_tasklist_agent_id_key ,
		NULL AS ekl_facility_id_key ,
		l1_fact.item_seller_id AS seller_id ,
		l1_fact.payment_type AS payment_mode ,
		NULL AS pos_id ,
		NULL AS transaction_id ,
		NULL AS agent_id ,
		NULL AS amount_collected ,
		l1_fact.item_seller_type AS seller_type ,
		l1_fact.item_is_dangerous AS shipment_dg_flag ,
		NULL AS shipment_fragile_flag ,
		l1_fact.seller_id_key ,
		NULL AS pos_id_key ,
		NULL AS shipment_agent_id_key ,
		NULL AS dummy1 ,
		NULL AS dummy2 ,
		NULL AS lzn_classification ,
		l1_fact.vendor_name
FROM bigfoot_external_neo.scp_fulfillment__fulfillment_tpl_shipment_intermediate_fact l1_fact
LEFT JOIN bigfoot_external_neo.scp_fulfillment__fulfillment_liteshipmentstatusevent_base_fact l0_fact ON l0_fact.sr_id = l1_fact.sr_id 
Left JOIN bigfoot_external_neo.scp_ekl__ekl_facility_hive_dim dim
ON l1_fact.facility_name = dim.name
WHERE UPPER(l1_fact.facility_name) like '%LAR%') FSD_TPL;